release:
  footer: |
    ## Docker Images
    - `paskalmaksim/gitlab-registry-cleaner:latest`
    - `paskalmaksim/gitlab-registry-cleaner:{{ .Tag }}`
dockers:
- goos: linux
  goarch: amd64
  image_templates:
  - paskalmaksim/gitlab-registry-cleaner:latest
  - paskalmaksim/gitlab-registry-cleaner:{{ .Tag }}
builds:
- dir: ./cmd/main
  env:
  - CGO_ENABLED=0
  flags:
  - -trimpath
  ldflags:
  - -X github.com/paskal-maksim/gitlab-registry-cleaner/pkg/api.version={{.Version}}-{{.ShortCommit}}-{{.Timestamp}}
  goos:
  - linux
  goarch:
  - amd64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
