version: '3'
services:
  kubernetes-manager:
    image: paskalmaksim/gitlab-registry-cleaner:dev
    volumes:
    - ./registry:/var/lib/registry:rw
    - /var/lib/node_exporter/textfile_collector/:/var/lib/node_exporter/textfile_collector/:rw
    environment:
    - GITLAB_URL=https://gitlab.my.org/api/v4
    - GITLAB_TOKEN=gitlab-token
    - RCLONE_CONFIG_S3_ACCESS_KEY_ID=s3-key
    - RCLONE_CONFIG_S3_SECRET_ACCESS_KEY=s3-access-key
    - RCLONE_CONFIG_S3_REGION=s3-region
    - SENTRY_ENVIRONMENT=gitlab-registry-cleaner
    - SENTRY_DSN=https://id@sentry.my.org
    entrypoint:
    - /bin/sh
    - -c
    - |
      set -ex

      # run registry in background
      registry serve /etc/docker/registry/config.yml&
      sleep 3

      # copy from object storage to local disk
      rclone --quiet sync s3:s3-bucket /var/lib/registry

      # manual remove stale registry
      #rm -rf /var/lib/registry/docker/registry/v2/repositories/some-group/some-project

      # check current folder with registry
      registry garbage-collect --dry-run --delete-untagged /etc/docker/registry/config.yml

      # detect stale docker registry tags 
      /app/gitlab-registry-cleaner

      # clean all tags folder
      cat cleanOldTags.sh | sh

      # clean garbage in registry
      registry garbage-collect --delete-untagged /etc/docker/registry/config.yml

      # copy local changes to object storage
      rclone --quiet sync /var/lib/registry s3:s3-bucket
      
      # create prometheus notification
      echo "docker_registry_cleaner $$(date +%s)" > /var/lib/node_exporter/textfile_collector/docker_registry_cleaner.proms