global:
  imageRegistry: ""

image:
  registry: docker.io
  repository: paskalmaksim/gitlab-registry-cleaner
  tag: v0.0.6
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: 100m
    memory: 100Mi

schedule: "0 0 * * *"

args: []
# - -snapshots
# - -metrics.pushgateway=http://prometheus-pushgateway.prometheus.svc.cluster.local:9091

env: []

tolerations: []
# - key: "kubernetes.azure.com/scalesetpriority"
#   operator: "Equal"
#   value: "spot"
#   effect: "NoSchedule"

garbageCollector:
  enabled: false
  schedule: "0 1 * * *"
  tolerations: []
  resources:
    requests:
      cpu: 100m
      memory: 100Mi

registry:
  enabled: false
  runInJob: false  # Run registry in a job, this will not run additional pods with registry
  image: registry:2.8.1
  imagePullPolicy: IfNotPresent
  port: 5000
  secret: M3u26yce98Py9Ebl0maAJubvpIZR5VD
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
  tolerations: []
  # - key: "kubernetes.azure.com/scalesetpriority"
  #   operator: "Equal"
  #   value: "spot"
  #   effect: "NoSchedule"
  env: []
  # - name: REGISTRY_STORAGE
  #   value: s3
  # - name: REGISTRY_STORAGE_S3_REGION
  #   value: aws-region
  # - name: REGISTRY_STORAGE_S3_BUCKET
  #   value: aws-bucket
  # - name: REGISTRY_STORAGE_S3_ACCESSKEY
  #   value: aws-key
  # - name: REGISTRY_STORAGE_S3_SECRETKEY
  #   value: aws-secret
