image: paskalmaksim/gitlab-registry-cleaner:dev
imagePullPolicy: Always

resources:
  requests:
    cpu: 100m
    memory: 100Mi

schedule: "0 5 * * *"

args: []
# - -metrics.pushgateway=http://prometheus-pushgateway.prometheus.svc.cluster.local:9091

env: []

tolerations: []
# - key: "kubernetes.azure.com/scalesetpriority"
#   operator: "Equal"
#   value: "spot"
#   effect: "NoSchedule"
