apiVersion: batch/v1
kind: CronJob
metadata:
  name: gitlab-registry-cleaner
spec:
  schedule: {{ .Values.schedule | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: {{ .Values.serviceAccount.name }}
{{ if .Values.tolerations }}
          tolerations:
{{ toYaml .Values.tolerations | indent 10 }}
{{ end }}
          containers:
          - name: gitlab-registry-cleaner
            image: {{ printf "%s/%s:%s" (default .Values.image.registry .Values.global.imageRegistry) .Values.image.repository .Values.image.tag }}
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            resources:
{{ toYaml .Values.resources | indent 14 }}

{{ if .Values.env }}
            env:
{{ toYaml .Values.env | indent 12 }}
{{ end }}

{{ if .Values.args }}
            args:
{{ toYaml .Values.args | indent 12 }}
{{ end }}
            {{ if .Values.registry.runInJob }}
            command:
            - sh
            - -c
            - |
              set -ex

              registry serve /etc/docker/registry/config.yml &

              /app/gitlab-registry-cleaner \
              {{- range .Values.args }}
              {{ . }} \
              {{- end }}
              -registry-wait

            {{ end }}
          restartPolicy: Never
      backoffLimit: 3
