apiVersion: batch/v1
kind: CronJob
metadata:
  name: gitlab-registry-cleaner
spec:
  schedule: {{ .Values.schedule | quote }}
  jobTemplate:
    spec:
      template:
        spec:
{{ if .Values.tolerations }}
          tolerations:
{{ toYaml .Values.tolerations | indent 10 }}
{{ end }}
          containers:
          - name: gitlab-registry-cleaner
            image: {{ .Values.image }}
            imagePullPolicy: {{ .Values.imagePullPolicy }}
            resources:
{{ toYaml .Values.resources | indent 14 }}

{{ if .Values.env }}
            env:
{{ toYaml .Values.env | indent 12 }}
{{ end }}

{{ if .Values.args }}
            args:
{{ toYaml .Values.args | indent 12 }}
{{ end }}
          restartPolicy: Never
      backoffLimit: 3
